[theme]
primaryColor = "#6349b1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[runner]
magicEnabled = true
fastReruns = true
